Fixes #202 : infinite redirection bug on password change
solidusio/solidus_auth_devise pull request #204
Opened 2021-01-17 04:31 UTC by nomad-mando

**Issue:** Infinite redirection was happening when, config `signout_after_password_change` was set to true, and user tries to change the password.

**Root cause:** When `signout_after_password_change` is enabled, on password change the user gets logged out. But in controller (`Spree::UsersController#update`) we were redirecting the user to account page. This was resulting in unauthorized access and previous URL being same account_edit page, it results in infinite redirection loop. ([Unauthorized access logic here](https://github.com/solidusio/solidus_auth_devise/blob/v2.5.2/lib/spree/auth/engine.rb#L78) tries to redirect to previous page first, which seems correct.)

**Solution:** When user is logged out already we shouldn't redirect it to the account edit page, so changing it to redirect on log_in page.

Fixes #202

2021-01-19 11:37 UTC, aldesantis requested changes
Thanks @nomad-mando, just a quick comment on readability!

2021-01-19 11:37 UTC, aldesantis commented on lib/controllers/frontend/spree/users_controller.rb
> +        Spree::Auth::Config[:signout_after_password_change] ? redirect_url = spree.login_url : bypass_sign_in(@user)
I find this inline assignment in a ternary operator quite hard to read. 😛 Could you just turn this into a regular if condition?

2021-01-20 02:55 UTC, nomad-mando commented
Thanks @aldesantis, I have addressed the comment now 👍

2021-01-20 05:28 UTC, nomad-mando commented
@aldesantis seems like some feature test started failing after that code refactoring. It doesn't look related to my change. Will check why it started failing later when I get chance.

2021-01-20 05:31 UTC, nomad-mando commented
same specs are also failing in master, I suspect they started failing after #203 got merged.

2021-01-20 17:38 UTC, aldesantis approved these changes

2021-01-20 17:39 UTC, aldesantis commented
@nomad-mando you're right, the failing specs are not related to your change.

Code-wise, this is looking good. Can you just squash the commits together so we don't pollute the history?

2021-01-20 19:41 UTC, jarednorman approved these changes
Looks good, just need things squashed and should be good.

2021-01-21 07:04 UTC, nomad-mando commented
@aldesantis / @jarednorman Done 👍 squashed both commits in to a single commit.

2021-01-21 12:23 UTC, merged